In [16]:
import numpy as np
from sklearn import *
import pandas as pd

In [17]:
## read dataset
data = pd.read_excel('Datasets/Residential-Building-Data-Set.xlsx', header = 1)
y_data = data.iloc[:,-2:]
X_data = data.iloc[:,:-2]
display(X_data)
display(y_data)

START YEAR  START QUARTER  COMPLETION YEAR  COMPLETION QUARTER  V-1  \
0            81              1               85                   1    1   
1            84              1               89                   4    1   
2            78              1               81                   4    1   
3            72              2               73                   2    1   
4            87              1               90                   2    1   
..          ...            ...              ...                 ...  ...   
367          83              4               86                   1   20   
368          81              2               82                   4   20   
369          84              4               86                   3   20   
370          82              3               84                   4   20   
371          80              1               81                   3   20   

        V-2     V-3     V-4  V-5      V-6  ...  V-20.4       V-21.4   V-22.4  \
0    3150.0   920.0   598.5  190  1010.84  ...      15   733.800000   815.50   
1    7600.0  1140.0  3040.0  400   963.81  ...      15  1143.800000  1316.30   
2    4800.0   840.0   480.0  100   689.84  ...      15   589.500000   765.80   
3     685.0   202.0    13.7   20   459.54  ...      12   197.679557   152.25   
4    3000.0   800.0  1230.0  410   631.91  ...      14  2220.600000  2244.10   
..      ...     ...     ...  ...      ...  ...     ...          ...      ...   
367  1350.0   350.0   108.0   80   251.37  ...      15  1082.500000  1176.50   
368   600.0   150.0    36.0   60   299.55  ...      15   746.800000   815.50   
369  1900.0   430.0   285.0  150   364.41  ...      15  1424.100000  1584.30   
370   510.0   160.0    30.6   60   245.28  ...      14   886.400000   909.20   
371   890.0   230.0    35.6   40   237.03  ...      15   629.900000   764.50   

      V-23.4  V-24.4  V-25.4  V-26.4    V-27.4    V-28.4     V-29.4  
0    1755.00  8002.0   60.74   54.26   2978.26  41407.00   601988.1  
1    8364.78  8393.0   90.95   89.79  11379.37  44835.00   929027.1  
2    1755.00  4930.0   38.70   32.04   1653.06  37933.00   377828.6  
3    1442.31  1456.0    9.73    8.34    686.16   8194.00   122031.7  
4    9231.76  9286.0  136.60  140.20   9821.00  48260.00  1734973.5  
..       ...     ...     ...     ...       ...       ...        ...  
367  8343.60  8382.0   87.27   85.56  10555.47  33626.25   865878.9  
368  1755.00  8013.0   62.78   56.45   3387.72  10646.75   606524.2  
369  8776.71  8799.0  101.00  101.89  13571.80  34474.50  1067772.0  
370  7930.66  8004.0   73.57   69.26   4756.68  21855.00   669640.3  
371  1755.00  8420.0   54.62   44.79   2206.19  40234.00   629797.2  

[372 rows x 107 columns]

V-9  V-10
0    2200   410
1    5000  1000
2    1200   170
3     165    30
4    5500   700
..    ...   ...
367  1100   150
368   740    80
369   860   220
370  1100   110
371   460    50

[372 rows x 2 columns]

In [18]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_data, y_data, random_state=42, test_size = 0.5)
display(X_train)
display(y_train)
indices = X_train.index
display(indices)

START YEAR  START QUARTER  COMPLETION YEAR  COMPLETION QUARTER  V-1  \
304          85              3               87                   4   18   
112          77              1               78                   2    4   
179          83              1               85                   1    8   
244          72              2               73                   2   14   
232          73              3               74                   4   13   
..          ...            ...              ...                 ...  ...   
71           83              2               85                   1    3   
106          83              1               85                   1    4   
270          78              3               80                   1   15   
348          77              2               78                   1   20   
102          76              1               77                   1    4   

        V-2    V-3    V-4  V-5     V-6  ...  V-20.4       V-21.4   V-22.4  \
304  1700.0  290.0  323.0  190  417.38  ...      15  1534.600000  1795.30   
112   930.0  240.0   93.0  100  770.16  ...      15   763.200000   582.80   
179  1580.0  363.0  284.4  180  615.49  ...      14  1005.000000  1270.50   
244   760.0  240.0   15.2   20  459.54  ...      12   197.679557   152.25   
232   730.0  230.0   14.6   20  397.43  ...      12   192.600000   232.90   
..      ...    ...    ...  ...     ...  ...     ...          ...      ...   
71   3240.0  630.0  680.4  210  715.52  ...      15  1014.900000  1104.70   
106   390.0  100.0   62.4  160  547.10  ...      14  1005.000000  1270.50   
270   750.0  200.0   45.0   60  423.07  ...      15   554.081966   663.97   
348   560.0  220.0   22.4   40  319.47  ...      15   229.200000   582.90   
102  1430.0  440.0   57.2   40  772.31  ...      15   225.700000   409.30   

      V-23.4  V-24.4  V-25.4  V-26.4    V-27.4    V-28.4     V-29.4  
304  9000.91  9022.0  109.02  112.00  10411.45  23548.00  1167697.4  
112  1755.00  4695.0   32.83   25.62   1936.75  36818.00   415431.1  
179  8002.21  8058.0   79.65   76.92   5062.76  43710.00   788018.3  
244  1442.31  1456.0    9.73    8.34    686.16   8194.00   122031.7  
232  1591.75  1601.0   11.91   10.41    363.13  16871.50   146872.1  
..       ...     ...     ...     ...       ...       ...        ...  
71   8148.33  8186.0   83.55   80.05   6703.06  11208.75   817526.9  
106  8002.21  8058.0   79.65   76.92   5062.76  43710.00   788018.3  
270  1755.00  5827.0   41.79   34.76   1527.55  19533.00   409677.9  
348  1755.00  4758.0   34.98   27.13   1859.50   9483.25   408321.5  
102  1750.00  4063.0   27.84   18.37   1549.44  35763.00   420700.5  

[186 rows x 107 columns]

V-9  V-10
304  1300   340
112   580   110
179  1000   250
244   100    30
232   200    30
..    ...   ...
71   2900   290
106  1300   220
270   470    80
348   400    50
102   350   120

[186 rows x 2 columns]

Int64Index([304, 112, 179, 244, 232, 117, 342, 358, 266, 336,
            ...
            214, 121, 371,  20, 188,  71, 106, 270, 348, 102],
           dtype='int64', length=186)

In [19]:

X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()
X_data = X_data.to_numpy()
y_data = y_data.to_numpy()
print((X_train.shape))


(186, 107)


In [20]:
linear_model = linear_model.LinearRegression()
linear_model.fit(X_train, y_train)
linear_model.score(X_test, y_test)
print((linear_model.coef_).shape)
print('score for LG = ', linear_model.score(X_test, y_test))

(2, 107)
score for LG =  0.9080998165656444


### Generative Linear Regression

---


In [21]:

data = data.to_numpy()
cov = np.cov(data.T)

In [22]:
## we must model p*(x, y) => we must model the joint => we must also model the covaraince of the lables matrix
## the covariance can be written as 
## i need the mean and co-varaince of the joint distribution that I am trying to estimate !
mu_net = np.mean(data, axis = 0)
mu_y = mu_net[-2:]
mu_x = mu_net[:-2]
precision = np.linalg.inv(cov)
print(mu_y.shape)

(2,)


In [23]:
y_size = 2
A_11 = precision[:-y_size,:-y_size]
A_22 = precision[-y_size:,-y_size:]
A_12 = precision[:-y_size, -y_size:]
A_21 = precision[-y_size:, :-y_size]

In [24]:
display(cov)

array([[ 1.74903052e+01, -5.53517085e-01,  1.74601339e+01, ...,
         1.91264405e+06,  3.06233719e+03,  5.12448483e+02],
       [-5.53517085e-01,  1.17371678e+00, -2.62977132e-01, ...,
        -4.08112633e+04, -1.21557220e+02, -2.26630655e+01],
       [ 1.74601339e+01, -2.62977132e-01,  1.78413181e+01, ...,
         1.90027532e+06,  3.12114229e+03,  5.27931702e+02],
       ...,
       [ 1.91264405e+06, -4.08112633e+04,  1.90027532e+06, ...,
         2.56777370e+11,  3.70712312e+08,  6.31612763e+07],
       [ 3.06233719e+03, -1.21557220e+02,  3.12114229e+03, ...,
         3.70712312e+08,  1.45463632e+06,  1.56137409e+05],
       [ 5.12448483e+02, -2.26630655e+01,  5.27931702e+02, ...,
         6.31612763e+07,  1.56137409e+05,  2.64477544e+04]])

In [25]:
class Model:
    def __init__(self, function,data):
        self.func = function
        self.data = data
    def predict(self, X):
        matrix = np.apply_along_axis(self.func, arr = X, axis=1, data= self.data)
        return matrix
    def explained_accuracy(self, X, y):
        return metrics.explained_variance_score(y, self.predict(X), multioutput='raw_values')

In [26]:
def GLG_pred(X, data):
    precision = data['precision']
    y_size = data['y_size']
    mu_x = data['mu_x']
    mu_y = data['mu_y']
    A_11 = precision[:-y_size,:-y_size]
    A_22 = precision[-y_size:,-y_size:]
    A_12 = precision[:-y_size, -y_size:]
    A_21 = precision[-y_size:, :-y_size]
    return (-1*np.linalg.inv(A_22) @ A_21 @ (X  - mu_x)) + mu_y

In [27]:
data = {'precision': precision, 'y_size':y_size, 'mu_x': mu_x, 'mu_y':mu_y}

In [28]:
print(y_train[0])
GLG_pred(X_train[0].T, data)

[1300  340]


array([1354.77009978,  334.04581751])

In [29]:
print(precision.shape)
(np.linalg.inv(A_22) @ A_21).shape
A_22.shape
A_21.shape

(109, 109)


(2, 107)

In [30]:
GLR = Model(GLG_pred, data=data)
print(GLR.predict(X_train).shape)
GLR.explained_accuracy(X_test, y_test)

(186, 2)


array([0.98711618, 0.98790674])

In [31]:
def Linear_Gaussian_pred(X, data):
    precision = data['precision']
    y_size = data['y_size']
    mu_x = data['mu_x']
    mu_y = data['mu_y']
    A_11 = precision[:-y_size,:-y_size]
    A_22 = precision[-y_size:,-y_size:]
    A_12 = precision[:-y_size, -y_size:]
    A_21 = precision[-y_size:, :-y_size]

In [32]:
# ## now for generative linear regression 
# #solve ERM using GD ???
# #in generative linear regression using MLE the sample mean and the sample deviation are the ones to go for !!
# m = y_data.shape[0]
# d_y = y_data.shape[1]
# mu_2 = np.sum(y_data, axis = 0)/(y_data.shape[0])
# print("means of labels = ", mu_2)
# sigma_2  = np.zeros((d_y,d_y))
# for i in range(d_y):
#     for j in range (d_y):
#         sigma_2[i][j] = (1/m)* np.sum((y_data[:, i] - mu_2[i])*(y_data[:, j] - mu_2[j]), axis = 0)

# print("Covaraince matrix = ", sigma_2)