In [42]:
import numpy as np


In [43]:
class Gaussian:
    def __init__(self, mu, sig, dim):
        self.dim = dim
        self.mu = mu
        self.sig = sig
    def density(self, x):
        if(self.dim != 1):
            norm_const = 1/( ( (2*np.pi)**(self.dim/2)) * (np.linalg.det(self.sig)**0.5) )
            exp_val = np.exp( -0.5 * (x - self.mu).T @ np.linalg.inv(self.sig)  @ (x - self.mu))
        else:
            norm_const = 1/(self.sig * np.sqrt(2 * np.pi) )
            exp_val = np.exp(-0.5 * (   (   (x - self.mu)/self.sig) **2)    )
        return norm_const* exp_val

In [44]:
mu_1 = np.array([0, 0])
mu_2  =  np.array([1,1])
mu_3 = np.array([-1, 1])

In [45]:
sig_1 = 0.7 * np.eye(2)
sig_2 = np.array(([0.8, 0.2], [0.2, 0.8]))
sig_3 = sig_2
display(sig_2)

array([[0.8, 0.2],
       [0.2, 0.8]])

In [46]:
g_1 = Gaussian(mu_1, sig_1,2)
g_2 = Gaussian(mu_2, sig_2, 2)
g_3 = Gaussian(mu_3, sig_3, 2)

In [47]:
x_1 = np.array([0.5, 0.5])
x_2  = np.array([-0.5, 0.5])

In [48]:
def density_vector(x , g_1, g_2, g_3):
    return np.array([g_1.density(x), g_2.density(x), g_3.density(x)])
print(density_vector(x_1, g_1,g_2, g_3))
print(density_vector(x_2, g_2, g_2, g_3))

[0.15908049 0.16001875 0.03022364]
[0.04983036 0.04983036 0.13545295]


In [49]:
class_x1   = np.argmax(density_vector(x_1, g_1, g_2, g_3), axis = 0) + 1
class_x2 = np.argmax(density_vector(x_2, g_1, g_2, g_3), axis = 0) + 1
print(class_x1 , class_x2)

2 1
