In [157]:
import numpy as np
from sklearn import *
import pandas as pd

In [158]:
## read dataset
data = pd.read_excel('Datasets/Residential-Building-Data-Set.xlsx', 0)
y_data = data.iloc[1:,-2:]
X_data = data.iloc[1:,:-2]
display(X_data)
display(y_data)

PROJECT DATES (PERSIAN CALENDAR) Unnamed: 1 Unnamed: 2 Unnamed: 3  \
1                                 81          1         85          1   
2                                 84          1         89          4   
3                                 78          1         81          4   
4                                 72          2         73          2   
5                                 87          1         90          2   
..                               ...        ...        ...        ...   
368                               83          4         86          1   
369                               81          2         82          4   
370                               84          4         86          3   
371                               82          3         84          4   
372                               80          1         81          3   

    PROJECT PHYSICAL AND FINANCIAL VARIABLES Unnamed: 5 Unnamed: 6 Unnamed: 7  \
1                                          1       3150        920      598.5   
2                                          1       7600       1140       3040   
3                                          1       4800        840        480   
4                                          1        685        202       13.7   
5                                          1       3000        800       1230   
..                                       ...        ...        ...        ...   
368                                       20       1350        350        108   
369                                       20        600        150         36   
370                                       20       1900        430        285   
371                                       20        510        160       30.6   
372                                       20        890        230       35.6   

    Unnamed: 8 Unnamed: 9  ... Unnamed: 97 Unnamed: 98 Unnamed: 99  \
1          190    1010.84  ...          15       733.8       815.5   
2          400     963.81  ...          15      1143.8      1316.3   
3          100     689.84  ...          15       589.5       765.8   
4           20     459.54  ...          12  197.679557      152.25   
5          410     631.91  ...          14      2220.6      2244.1   
..         ...        ...  ...         ...         ...         ...   
368         80     251.37  ...          15      1082.5      1176.5   
369         60     299.55  ...          15       746.8       815.5   
370        150     364.41  ...          15      1424.1      1584.3   
371         60     245.28  ...          14       886.4       909.2   
372         40     237.03  ...          15       629.9       764.5   

    Unnamed: 100 Unnamed: 101 Unnamed: 102 Unnamed: 103 Unnamed: 104  \
1           1755         8002        60.74        54.26      2978.26   
2        8364.78         8393        90.95        89.79     11379.37   
3           1755         4930         38.7        32.04      1653.06   
4        1442.31         1456         9.73         8.34       686.16   
5        9231.76         9286        136.6        140.2         9821   
..           ...          ...          ...          ...          ...   
368       8343.6         8382        87.27        85.56     10555.47   
369         1755         8013        62.78        56.45      3387.72   
370      8776.71         8799          101       101.89      13571.8   
371      7930.66         8004        73.57        69.26      4756.68   
372         1755         8420        54.62        44.79      2206.19   

    Unnamed: 105 Unnamed: 106  
1          41407     601988.1  
2          44835     929027.1  
3          37933     377828.6  
4           8194     122031.7  
5          48260    1734973.5  
..           ...          ...  
368     33626.25     865878.9  
369     10646.75     606524.2  
370      34474.5      1067772  
371        21855     669640.3  
372        40234     629797.2  

[372 rows x 107 columns]

OUTPUTS Unnamed: 108
1      2200          410
2      5000         1000
3      1200          170
4       165           30
5      5500          700
..      ...          ...
368    1100          150
369     740           80
370     860          220
371    1100          110
372     460           50

[372 rows x 2 columns]

In [159]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_data, y_data, random_state=42, test_size = 0.5)
display(X_train)
display(y_train)
indices = X_train.index

PROJECT DATES (PERSIAN CALENDAR) Unnamed: 1 Unnamed: 2 Unnamed: 3  \
305                               85          3         87          4   
113                               77          1         78          2   
180                               83          1         85          1   
245                               72          2         73          2   
233                               73          3         74          4   
..                               ...        ...        ...        ...   
72                                83          2         85          1   
107                               83          1         85          1   
271                               78          3         80          1   
349                               77          2         78          1   
103                               76          1         77          1   

    PROJECT PHYSICAL AND FINANCIAL VARIABLES Unnamed: 5 Unnamed: 6 Unnamed: 7  \
305                                       18       1700        290        323   
113                                        4        930        240         93   
180                                        8       1580        363      284.4   
245                                       14        760        240       15.2   
233                                       13        730        230       14.6   
..                                       ...        ...        ...        ...   
72                                         3       3240        630      680.4   
107                                        4        390        100       62.4   
271                                       15        750        200         45   
349                                       20        560        220       22.4   
103                                        4       1430        440       57.2   

    Unnamed: 8 Unnamed: 9  ... Unnamed: 97 Unnamed: 98 Unnamed: 99  \
305        190     417.38  ...          15      1534.6      1795.3   
113        100     770.16  ...          15       763.2       582.8   
180        180     615.49  ...          14        1005      1270.5   
245         20     459.54  ...          12  197.679557      152.25   
233         20     397.43  ...          12       192.6       232.9   
..         ...        ...  ...         ...         ...         ...   
72         210     715.52  ...          15      1014.9      1104.7   
107        160      547.1  ...          14        1005      1270.5   
271         60     423.07  ...          15  554.081966      663.97   
349         40     319.47  ...          15       229.2       582.9   
103         40     772.31  ...          15       225.7       409.3   

    Unnamed: 100 Unnamed: 101 Unnamed: 102 Unnamed: 103 Unnamed: 104  \
305      9000.91         9022       109.02          112     10411.45   
113         1755         4695        32.83        25.62      1936.75   
180      8002.21         8058        79.65        76.92      5062.76   
245      1442.31         1456         9.73         8.34       686.16   
233      1591.75         1601        11.91        10.41       363.13   
..           ...          ...          ...          ...          ...   
72       8148.33         8186        83.55        80.05      6703.06   
107      8002.21         8058        79.65        76.92      5062.76   
271         1755         5827        41.79        34.76      1527.55   
349         1755         4758        34.98        27.13       1859.5   
103         1750         4063        27.84        18.37      1549.44   

    Unnamed: 105 Unnamed: 106  
305        23548    1167697.4  
113        36818     415431.1  
180        43710     788018.3  
245         8194     122031.7  
233      16871.5     146872.1  
..           ...          ...  
72      11208.75     817526.9  
107        43710     788018.3  
271        19533     409677.9  
349      9483.25     408321.5  
103        35763     420700.5  

[186 rows x 107 columns]

OUTPUTS Unnamed: 108
305    1300          340
113     580          110
180    1000          250
245     100           30
233     200           30
..      ...          ...
72     2900          290
107    1300          220
271     470           80
349     400           50
103     350          120

[186 rows x 2 columns]

In [160]:

X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()
X_data = X_data.to_numpy()
y_data = y_data.to_numpy()
print((X_train))


[[85 3 87 ... 10411.45 23548 1167697.4]
 [77 1 78 ... 1936.75 36818 415431.1]
 [83 1 85 ... 5062.76 43710 788018.3]
 ...
 [78 3 80 ... 1527.55 19533 409677.9]
 [77 2 78 ... 1859.5 9483.25 408321.5]
 [76 1 77 ... 1549.44 35763 420700.5]]


In [161]:
linear_model = linear_model.LinearRegression()
linear_model.fit(X_train, y_train)
linear_model.score(X_test, y_test)
print((linear_model.coef_).shape)

(2, 107)


In [162]:
## now for generative linear regression 
#solve ERM using GD ???
#in generative linear regression using MLE the sample mean and the sample deviation are the ones to go for !!
m = y_data.shape[0]
d_y = y_data.shape[1]
mu_2 = np.sum(y_data, axis = 0)/(y_data.shape[0])
print("means of labels = ", mu_2)
sigma_2  = np.zeros((d_y,d_y))
for i in range(d_y):
    for j in range (d_y):
        sigma_2[i][j] = (1/m)* np.sum((y_data[:, i] - mu_2[i])*(y_data[:, j] - mu_2[j]), axis = 0)

print("Covaraince matrix = ", sigma_2)

means of labels =  [1387.4327956989248 232.6478494623656]
Covaraince matrix =  [[1450726.0035481   155717.6846673 ]
 [ 155717.6846673    26376.65824806]]


In [163]:
# now to do the same thing but with the joint
#z = [x y]
z = data.iloc[1:,:]
z = z.to_numpy()
m = z.shape[0]
d = z.shape[1]
mean = np.mean(z, axis  = 0)
print(mean.shape)
cov  = np.ones((d, d))
for i in range (d):
    for j in range (d):
        cov[i][j]  = np.mean((z [:, i] - mean[i]) * (z[:, j] - mean[j]), axis = 0)

print(cov.shape)
precision = np.linalg.inv(cov)
A_11 = precision[0:107, 0:107]
A_22 = precision[107:109 , 107:109]
A_12 = precision[0:107 , 107:109]
A_21 = precision[107:109, 0:107]
mu_1 = mean[0:107]
mu_2 = mean[107:109]
bayes_coeff = np.linalg.inv(A_22)@A_21
bayes_constant  = mu_2 - bayes_coeff @ mu_1 
print(bayes_coeff.shape)
def bayes_predictor(bayes_coef, X_test, bayes_constant):
    return X_test @ bayes_coef.T + bayes_constant

y_pred = bayes_predictor(bayes_coeff, X_train, bayes_constant)
metrics.explained_variance_score(y_train, y_pred)

(109,)
(109, 109)
(2, 107)


-2.876876685651715